/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dumbledores_office.glb --draco 
Author: zack_graham (https://sketchfab.com/zack_graham)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dumbledores-office-c5fdffa78c9442bb93a88c386d4ad53d
Title: Dumbledore's Office
*/

import { useGraph } from "@react-three/fiber";
import { SkeletonUtils } from "three-stdlib";
import { useGLTF } from "@react-three/drei";
import React from "react";

export function DumbledoresOffice(props) {
  const { scene } = useGLTF("/dumbledores_office.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  return (
    <group {...props} dispose={null} receiveShadow>
      <primitive object={nodes._rootJoint} />
    </group>
  );
}

useGLTF.preload("/dumbledores_office.glb");
