/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lanscape_jam_gadang.glb --draco 
Author: dekahobby (https://sketchfab.com/dekahobby)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lanscape-jam-gadang-0fb9172e572240cca4f1d597b3be90a8
Title: Lanscape jam gadang
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function LandscapeJamGadang(props) {
  const { nodes, materials } = useGLTF("/lanscape_jam_gadang.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-9.729, -18.693, 19.436]}
        rotation={[-0.034, 0.004, 3.127]}
        scale={0.593}
      >
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.low_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.low_Material_u1_v2}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.low_Material_u2_v1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/lanscape_jam_gadang.glb");
