/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 the_smoking_room.glb --draco 
Author: The Hallwyl Museum (Hallwylska museet) (https://sketchfab.com/TheHallwylMuseum)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-smoking-room-2247ed77976a40b6ae81271cd6b149c8
Title: The Smoking Room
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function TheSmokingRoom(props) {
  const { nodes, materials } = useGLTF("/the_smoking_room.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.245}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.model_Material_u1_v1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/the_smoking_room.glb");
